# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.6.1
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-08-24T21:55:40Z"
  labels:
    app: veilid
  name: veilid
spec:
  containers:
  - image: docker.io/gangrif/veilid-server-ubi:latest
    name: server
    ports:
    - containerPort: 5150
      hostIP: 192.168.200.210
      hostPort: 5150
    securityContext: {}
    volumeMounts:
    - mountPath: /config
      name: veilid-server-config-pvc
    - mountPath: /var/db/veilid-server
      name: veilid-server-data-pvc

  volumes:
  - name: veilid-server-data-pvc
    persistentVolumeClaim:
      claimName: systemd-veilid-server-data 
  - name: veilid-server-config-pvc
    persistentVolumeClaim:
      claimName: systemd-veilid-server-config


